#入力説明
#シングルクォートで囲まれた部分はエスケープせずに記入可能

# @ymd@ ⇒ 西暦
# @year@ ⇒ 年（西暦）
# @month@ ⇒ 月
# @day@ ⇒ 日
# @hms@ ⇒ 時分秒
# @path@ ⇒ ルートパス
# @#@ ⇒ 数値の置換え　#の数分の桁数にする（10桁まで）


#プロジェクト設定（削除禁止）
projectSettings:
    login_id: 1

#システム設定（削除禁止）
systeSetting:
    searchLimit: 10000 #データ検索の1ページのレコード数

#権限（削除禁止）
authority:
    operator: 0 #オペレーター権限
    leader: 1 #リーダー権限
    supervisor: 2 #スーパーバイザー権限
    administrator: 9 #管理者権限

#JavaScript
script:
    dir: "scripts"
    load: "file_load.js" 
    imp: "file_import.js"


#データベース設定
# Schema + _connection
# provider Accdb, Accdb2019, SqlServer, Sqllite, MySql

db_Connection:
    provider: "Sqlite"
    host: ""
    dataBaseName: '.\db\db.sqlite'
    port: ""
    userId: ""
    password: ""

setting_Connection:
    provider: "Sqlite"
    host: ""
    dataBaseName: '.\db\setting.sqlite'
    port: ""
    userId: ""
    password: ""

user_Connection:
    provider: "Sqlite"
    host: ""
    dataBaseName: '.\db\user.sqlite'
    port: ""
    userId: ""
    password: ""

beatle_Connection:
    provider: "SqlServer"
    host: '10.0.0.2\SQLEXPRESS'
    dataBaseName: 'Beatle01DB'
    port: ""
    userId: "bea01mgr"
    password: "bea01mgr"

code_Connection:
    provider: "Sqlite"
    host: ""
    dataBaseName: '.\db\roukin_code.sqlite'
    port: ""
    userId: ""
    password: ""

#ろうきんAML案件設定
#sjis, utf8, utf8bom, utf16le, utf16lebom, utf16be, utf16bebom
roukin_setting:
    img_root_path: 'D:\03.案件\ら\02.労働金庫連合会\01.AML業務\04.テストデータ\01.自前テスト\画像'
    exp_root_path: 'D:\03.案件\ら\02.労働金庫連合会\01.AML業務\04.テストデータ\01.自前テスト'
    match_root_path: 'D:\03.案件\ら\02.労働金庫連合会\01.AML業務\04.テストデータ\01.自前テスト\マッチングデータ'
    siwake_root_path: 'D:\03.案件\ら\02.労働金庫連合会\01.AML業務\04.テストデータ\01.自前テスト\仕分データ'
    fubifuchaku_root_path: 'D:\03.案件\ら\02.労働金庫連合会\01.AML業務\04.テストデータ\01.自前テスト\不備状不着仕分データ'
    img_dir: '画像' #申請書画像ディレクトリ
    fubi_img_dir: '不備画像'     #不備画像ディレクトリ        
    customer_info_name: 'KJOUHOUKOUSHINA'               #顧客情報変更データ
    customer_dir: '勘定系@ymd@'                         #勘定系用データのディレクトリ
    resuponse_res_name: 'ANS_KOKYAKUKANRI.txt'          #回答結果顧客管理データ
    answer_res_image_name: 'ANS_IMAGEKANRI.txt'         #回答結果イメージ管理データ
    answer_dir: '本人確認システム@ymd@'                 #本人確認システム用データのディレクトリ
    safe_box_admin_name: 'ANS_DATA_KINKOJIMU_@ymd@.txt' #金庫事務用データ
    safe_box_admin_dir: '金庫事務用@ymd@'               #金庫事務用データのディレクトリ
    max_count: '2500' #1納品当たりの最大件数

    nouhinzumi_dantai_blt: '団体_50_勘定系納品済_@ymd@_@hms@.txt' #団体納品済みデータ
    nouhinzumi_kojin_blt: '個人_20_勘定系納品済_@ymd@_@hms@.txt'  #個人納品済みデータ

    fubi_data_name: 'ANS_KOKYAKUKANRI_KINKOJIMU_@ymd@.txt'      #不備対象データ
    fubi_img_data_name: 'ANS_IMAGEKANRI_KINKOJIMU_@ymd@.txt'    #不備対象イメージ管理データ
    fubi_nouhin_img_dir: '不備状画像' #不備状画像ディレクトリ'
    fubi_img_zip_name: 'ANS_IAMGE_KINKOJIMU_@ymd@.zip'          #不備対象イメージZIPファイル
    fubi_call_zip_name: '不備状画像_@ymd@.zip'          #不備対象コールZIPファイル
    fubi_call_zip_password: '' #不備対象コールZIPファイルのパスワード

    fuchaku_name: '還付データ_@ymd@_xxx.txt' #不着データ

    dp_dir: 'DP連携@ymd@'                        #DP連携データのディレクトリ
    dp_file_kojin: '個人_本人確認記録書.txt'     #DP連携データ個人
    dp_file_dantai: '法人_本人確認記録書.txt'    #DP連携団体データ

    punch_img_dir: 'パンチ画像'   #パンチ画像ディレクトリ
    punch_zip_name: '労働金庫連合会_パンチ用画像_@ymd@.zip' #パンチ画像連携ファイル名
    punch_zip_password: '' #パンチ画像連携ファイルのパスワード

    match_name: '労金_不備状丁合_@ymd@_@hms@.txt' #マッチングデータ
    siwake_name: '労金_申請書仕分'  #申請書仕分データ
    fubifuchaku_name: '労金_不備不着仕分_@ymd@_@hms@.txt' #不備状不着仕分データ

    industry_etc_code: '620050' #（個人）業種その他コード
    jpn_code: '0100' #日本国コード

    exp_webcas_file_name: "個人_10_WEBデータ_@ymd@_@hms@_@#@.csv"    #個人WEBデータ
    exp_webcas_file_delimiter: ","
    exp_webcas_file_mojicode: "utf8bom"

    #1Byte文字コードの許可範囲
    allow1byte: '[0x00,0x00][0x20,0x20][0x28,0x28][0x29,0x29][0x2C,0x39][0x41,0x5A][0x5C,0x5C][0xA2,0xA2][0xA3,0xA3][0xA6,0xDF]'
    #2Byte文字コードの許可範囲
    allow2byte: '[8140,84BE][889F,EAA2]'

    exp_rew_ok_file_name: "団体_40_審査結果正常_@ymd@_@hms@_@#@.csv"    #団体審査正常
    exp_rew_ng_file_name: "団体_30_審査結果不備_@ymd@_@hms@_@#@.csv"    #団体審査不備
    fubi_print_name: "団体_32_不備状印刷結果_@ymd@_@hms@.txt"        #団体不備状印刷結果




