#入力説明
#シングルクォートで囲まれた部分はエスケープせずに記入可能

# @ymd@ ⇒ 西暦
# @year@ ⇒ 年（西暦）
# @month@ ⇒ 月
# @day@ ⇒ 日
# @hms@ ⇒ 時分秒
# @path@ ⇒ ルートパス
# @#@ ⇒ 数値の置換え　#の数分の桁数にする（10桁まで）


#プロジェクト設定（削除禁止）
projectSettings:
    projectName: "労働金庫連合会　AML業務"
    projectVersion: "1.0.0"
    login_id: 1

#システム設定（削除禁止）
systeSetting:
    searchLimit: 10000 #データ検索の1ページのレコード数

#権限（削除禁止）
authority:
    operator: 0 #オペレーター権限
    leader: 1 #リーダー権限
    supervisor: 2 #スーパーバイザー権限
    administrator: 9 #管理者権限

#JavaScript
script:
    dir: "scripts"
    load: "file_load.js" 
    imp: "file_import.js"


#データベース設定
# Schema + _connection
# provider Accdb, Accdb2019, SqlServer, Sqllite, MySql

db_Connection:
    provider: "Sqlite"
    host: ""
    dataBaseName: '.\db\db.sqlite'
    port: ""
    userId: ""
    password: ""

setting_Connection:
    provider: "Sqlite"
    host: ""
    dataBaseName: '.\db\setting.sqlite'
    port: ""
    userId: ""
    password: ""

user_Connection:
    provider: "Sqlite"
    host: ""
    dataBaseName: '.\db\user.sqlite'
    port: ""
    userId: ""
    password: ""

beatle_Connection:
    provider: "SqlServer"
    host: '10.0.0.2\SQLEXPRESS'
    dataBaseName: 'Beatle01DB'
    port: ""
    userId: "bea01mgr"
    password: "bea01mgr"

code_Connection:
    provider: "Sqlite"
    host: ""
    dataBaseName: '.\db\roukin_code.sqlite'
    port: ""
    userId: ""
    password: ""

#ろうきんAML案件設定
#sjis, utf8, utf8bom, utf16le, utf16lebom, utf16be, utf16bebom
roukin_setting:
    img_root_path: 'D:\04.VisualStudio\ろうきん\img'
    exp_root_path: 'D:\04.VisualStudio\ろうきん\AML業務\Documents\テストデータ'
    customer_info_name: 'KJOUHOUKOUSHINA'               #顧客情報変更データ
    customer_dir: '勘定系@ymd@'                         #勘定系用データのディレクトリ
    resuponse_res_name: 'ANS_KOKYAKUKANRI.txt'          #回答結果顧客管理データ
    answer_res_image_name: 'ANS_IMAGEKANRI.txt'         #回答結果イメージ管理データ
    answer_dir: '本人確認システム@ymd@'                 #本人確認システム用データのディレクトリ
    safe_box_admin_name: 'ANS_DATA_KINKOJIMU_@ymd@.txt' #金庫事務用データ
    safe_box_admin_dir: '金庫事務用@ymd@'               #金庫事務用データのディレクトリ

    industry_etc_code: '620050' #（個人）業種その他コード

    fubi_print_name: "10_不備状印刷_@ymd@_@hms@.txt"
    exp_webcas_file_name: "PER_01_data_@ymd@_@hms@_@#@.csv"
    exp_webcas_file_delimiter: ","
    exp_webcas_file_mojicode: "utf8bom"
    exp_grp_res_file_name: "GRP_51_data_@ymd@_@hms@_@#@.csv"
    exp_per_res_file_name: "PER_21_data_@ymd@_@hms@_@#@.csv"
    exp_rew_ok_file_name: "団体_40_data_@ymd@_@hms@_@#@.csv"
    exp_rew_ng_file_name: "団体_30_data_@ymd@_@hms@_@#@.csv"




